proiect_IS-main/pages/urls.py
# pages/urls.py
from django.urls import path
from .views import newCV
from .views import myCv
from .views import qr
from .views import qaa

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('cv/',newCV ),
     path('myCV/', myCv),
     path('qr/', qr),
     path('qaa/', qaa),
    
]

proiect_IS-main/accounts/models.py
from django.db import models

# Create your models here.
# accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    # add additional fields in here

    def __str__(self):
        return self.email

proiect_IS-main/cv/models.py
# import the standard Django Model
# from built-in library
from django.db import models
   
# declare a new model with a name "GeeksModel"
class GeeksModel(models.Model):
  
    # fields of the model
    title = models.CharField(max_length = 200)
    description = models.TextField()
  
    # renames the instances of the model
    # with their title name
    def __str__(self):
        return self.title

proiect_IS-main/accounts/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

proiect_IS-main/cv/forms.py
from django import forms
from .models import GeeksModel
  
  
# creating a form
class GeeksForm(forms.ModelForm):
  
    # create meta class
    class Meta:
        # specify model to be used
        model = GeeksModel
  
        # specify fields to be used
        fields = [
            "title",
            "description",
        ]

proiect_IS-main/accounts/views.py
from django.shortcuts import render

# Create your views here.

proiect_IS-main/cv/views.py
from django.shortcuts import render
from EmailForm import *

# relative import of forms
from .models import GeeksModel
from .forms import GeeksForm
from django import forms
import smtplib


  
def sendMail(request):
    
        messageSent = False
        recipient = forms.EmailField()
        message = forms.CharField(widget=forms.Textarea)
        server=smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login("maria.vasilache02@gmail.com", "qgrqmaoreadfcszp")

        # check if form has been submitted
        if request.method == 'POST':

            form = EmailForm(request.POST)

            # check if data from the form is clean
            if form.is_valid():
                cd = form.cleaned_data
                subject = "CV-issue"
                message = cd['message']
                emm=cd['recipient']
                files = request.FILES.getlist('attach')
                #attach = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
            # server.sendmail("maria.vasilache02@gmail.com", ["maria.vasilache02@gmail.com", [cd['recipient']]], subject+"\n"+message) 
            # server.quit()
                files
                email = EmailMessage()

                email['Subject'] = subject
                email['From'] = emm
                email['To'] = 'maria.vasilache02@gmail.com'
                email.set_content("S-a primit o solicitare de la "+emm+"\n\n"+ "Mesajul transmis:\n "+message+"\n"+"\nATENTIE: Este posibil sa fie incarcate atasamenta!!")

                with open('D:\An3\IS\P1\cv.pdf', 'rb') as content_file:
                    
                    content = content_file.read()
                    email.add_attachment(content, maintype='application', subtype='pdf', filename='cv.pdf')

                server.send_message(email)
                

                messageSent = True

        else:
            form = EmailForm()

        return render(request, 'QR/QandA.html', {'form': form,'messageSent': messageSent})

proiect_IS-main/pages/views.py
from qrPage import qr
from data import *
from form import *
from qaForm import *
from getDetaliinewCV import *
from newCV import *
from downloadCV import *


from django.shortcuts import render
from django import forms
# Create your views here.
# pages/views.py
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.shortcuts import render
import qrcode
import qrcode.image.svg
from io import BytesIO
from django.core import mail
from django.core.mail import send_mail
from django.core import mail
import smtplib
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMessage
from email.message import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render
from .data import *
import html
from django.utils.html import escape
import mimetypes
import os
from wsgiref.util import setup_testing_defaults
from wsgiref.simple_server import make_server
from wsgiref.util import FileWrapper
from django.http import StreamingHttpResponse
import pdfkit as pdf

proiect_IS-main/templates/Pdf/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demo</title>
</head>
<body>
    <form action="validate" method="post">
        {% csrf_token %}
        
        Username : <input type="text" name="user" ><br><br>
        Password : <input type="text" name = "pass"><br><br>


        <input type="submit" value="Submit">
    </form>
</body>
</html>

proiect_IS-main/templates/Pdf/pdfReport.html
{% load static %}

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ titleCV }}</title>
    <link type="image/x-icon" rel="shortcut icon" href="{% static 'img/cv.ico' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
      <div class="alert alert-primary" role="alert">
                CV
     </div>
    <div class="general__area">
        <div class="top__area">
            <div class="bio__area">
                <div class="photo__area"><img url="{% static 'img/photo3.png' %}" alt="{{ yourName | safe }}" /></div>
                <div class="info__area">
                    <p class="name"><br></br>Nume si Prenume: {{ yourName }}</p>
                    <p class="profession">Your Profession {{ profession }}</p>
                    <p class="bio">Your Bio: {{ yourBio }}</p>
                </div>
            </div>
            
            <div class="personal__area">
                <p class="country">{{ yourCountry }}</p>
                <div class="social__area">
                    <br></br>Your Contact: {{ yourContact | safe }}
                </div>
                <p class="birth__date">{{ yourBirthday }}</p>
            </div>
            <div class="exp__area">
                {% if yourSkills %}
                <br></br> Your Skills: 
                <div class="exp__box">
                    <ol aria-label="Skills">
                         {{ yourSkills | safe }}
                    </ol>
                </div>
                {% endif %}
                {% if yourHobbies %}
                <br></br>Your Hobbies
                <div class="exp__box">
                    <ol aria-label="Hobbies">
                        {{ yourHobbies | safe }}
                    </ol>
                </div>
                {% endif %}
               
            </div>
        </div>
        <div class="mid__area">
            <div class="status__area">
                {% if yourEdu %}
                <br></br>Your Edu
                <div class="education__area">
                    <ol aria-label="Education">
                        {{ yourEdu | safe }}
                    </ol>
                </div>
                {% endif %}
                {% if yourWork %}
                <br></br>Your Work
                <div class="work__area">
                    <ol aria-label="Work">
                        {{ yourWork | safe }}
                    </ol>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="bottom__area">
            <div class="history__area">
                <br></br>Your Project
                {% if yourProject %}
                <div class="project__area">
                    <ol aria-label="Projects">
                        {{ yourProject | safe }}
                    </ol>
                </div>
                {% endif %}
              
            </div>
        </div>
    </div>
    <footer>{{ footerText | safe }}</footer>
    <script type="text/javascript" src="/static/js/vanilla-tilt.min.js"></script>
    <script type="text/javascript" src="/static/js/parallax.js"></script>
    {% comment %} <a href="/myCV/downloadFile/" class="btn2 btn-success btn-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Download File" tabindex="-1" role="button" aria-disabled="true"></i>Download File</a>
     {% endcomment %}
    <br></br>
</body>

</html>

proiect_IS-main/templates/Pdf/validate.html
{% load static %}

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ titleCV }}</title>
    
    <link type="image/x-icon" rel="shortcut icon" href="{% static 'img/cv.ico' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>

<body>
    <div class="p-4">
        <br></br>
        <a href="{% url 'home' %}" class="btn btn-primary btn-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Enter in your account" tabindex="-1" role="button" aria-disabled="true"><i class="fa fa-home"></i>Home</a>
    </div> 
    <div class="general__area">
        <div class="top__area">
            <div class="bio__area">
                <div class="photo__area"><img src={{attach}} /></div>
                <div class="info__area">
                    <p class="prenume">Name: {{ prenume }}</p>
                    <p class="profession">Profession: {{ profession }}</p>
                    <p class="bio">The Current Job: {{ yourBio }}</p>
               </div>
            </div>
            <div class="personal__area">
                <p class="country">Country: {{ yourCountry }}</p>
                <div class="social__area">
                    {{ yourContact | safe }}
                </div>
                <p class="birth__date">{{ yourBirthday }}</p>
            </div>
            <div class="exp__area">
                {% if yourSkills %}
                <div class="exp__box">
                    <ol aria-label="Skills">
                        {{ yourSkills | safe }}
                    </ol>
                </div>
                {% endif %}
                {% if yourHobbies %}
                <div class="exp__box">
                    <ol aria-label="Hobbies">
                        {{ yourHobbies | safe }}
                    </ol>
                </div>
                {% endif %}
               
            </div>
        </div>
        <div class="mid__area">
            <div class="status__area">
                {% if yourEdu %}
                <div class="education__area">
                    <ol aria-label="Education">
                        {{ yourEdu | safe }}
                    </ol>
                </div>
                {% endif %}
                {% if yourWork %}
                <div class="work__area">
                    <ol aria-label="Work">
                        {{ yourWork | safe }}
                    </ol>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="bottom__area">
            <div class="history__area">
                {% if yourProject %}
                <div class="project__area">
                    <ol aria-label="Projects">
                        {{ yourProject | safe }}
                    </ol>
                </div>
                {% endif %}
              
            </div>
        </div>
    </div>

    <a class ="btn btn-primary" href="{%url 'pdf_report_create' %}"> Create PDF </a>
   
        <footer>{{ footerText | safe }}</footer>
    <script type="text/javascript" src="{% static 'js/vanilla-tilt.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
    
    <br></br>
</body>

</html>

proiect_IS-main/templates/QR/MyCV.html
{% load static %}

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ titleCV }}</title>
    <link type="image/x-icon" rel="shortcut icon" href="{% static 'img/cv.ico' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>

<body>
    <div class="p-4">
        <br></br>
        <a href="{% url 'home' %}" class="btn btn-primary btn-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Enter in your account" tabindex="-1" role="button" aria-disabled="true"><i class="fa fa-home"></i>Home</a>
    </div> 
    <div class="general__area">
        <div class="top__area">
            <div class="bio__area">
                <div class="photo__area"><img src="{% static 'img/photo3.png' %}" alt="{{ yourName | safe }}" /></div>
                <div class="info__area">
                    <p class="name">{{ yourName }}</p>
                    <p class="profession">{{ yourProfession }}</p>
                    <p class="bio">{{ yourBio }}</p>
                </div>
            </div>
            <div class="personal__area">
                <p class="country">{{ yourCountry }}</p>
                <div class="social__area">
                    {{ yourContact | safe }}
                </div>
                <p class="birth__date">{{ yourBirthday }}</p>
            </div>
            <div class="exp__area">
                {% if yourSkills %}
                <div class="exp__box">
                    <ol aria-label="Skills">
                        {{ yourSkills | safe }}
                    </ol>
                </div>
                {% endif %}
                {% if yourHobbies %}
                <div class="exp__box">
                    <ol aria-label="Hobbies">
                        {{ yourHobbies | safe }}
                    </ol>
                </div>
                {% endif %}
               
            </div>
        </div>
        <div class="mid__area">
            <div class="status__area">
                {% if yourEdu %}
                <div class="education__area">
                    <ol aria-label="Education">
                        {{ yourEdu | safe }}
                    </ol>
                </div>
                {% endif %}
                {% if yourWork %}
                <div class="work__area">
                    <ol aria-label="Work">
                        {{ yourWork | safe }}
                    </ol>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="bottom__area">
            <div class="history__area">
                {% if yourProject %}
                <div class="project__area">
                    <ol aria-label="Projects">
                        {{ yourProject | safe }}
                    </ol>
                </div>
                {% endif %}
              
            </div>
        </div>
    </div>
    <footer>{{ footerText | safe }}</footer>
    <script type="text/javascript" src="{% static 'js/vanilla-tilt.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
    {% comment %} <a href="/myCV/downloadFile/" class="btn2 btn-success btn-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Download File" tabindex="-1" role="button" aria-disabled="true"></i>Download File</a>
     {% endcomment %}
    <br></br>
</body>

</html>

proiect_IS-main/templates/QR/QRcode.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <title>QR</title>
    <link rel="icon" type="image/x-icon" href="https://www.logolynx.com/images/logolynx/f7/f729f82b040ce6f1cbc0b812028371e8.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script>
        const ERROR_CORRECTION_LEVEL = "L";
        const MAX_TEXT_LENGTH = 2950;// Only valid for Error Correction Level L
        const QR_SIZE = 0;
    </script>
    
</head>
<body>
   
<div class="p-3">
    <a href="{% url 'home' %}" class="btn btn-primary btn-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Enter in your account" tabindex="-1" role="button" aria-disabled="true"><i class="fa fa-home"></i>Home</a>
</div>    
    <noscript><div class="error">You need to enable JavaScript to use this page</div></noscript>
    <div id="error" class="error">BUG: You should not see this text</div> <br></br>
    <div class ="container mb-7" style="max-width: 640px;">
        <div class="alert alert-primary" role="alert">
           
          <h2> EUROPASS</h2>
        </div>
      
        <div class="card mb-3" style="max-width: 640px;">
        
        
              <img src="https://cityworld.gr/wp-content/uploads/2014/05/europass.png" class="img-fluid rounded-start" alt="...">
            </div>
             
    
            <div class="alert alert-primary" role="alert">
                <h2> 
                Scan the QR code to access the site</h2>
              </div>

               
                
            </div>
          </div>
        </div>
      
      
      
      </form>
      </div>
      
      </body>
   
    <div id="qrcode"></div>

    <style>
        * {
            box-sizing: border-box;
        }
        h1 {
            text-align: center;
        }
     

        
        .bg-light {
    background-color: rgb(0 123 255 / 0%)!important;
}
a:hover {
    color: #b3009d;
    text-decoration: underline!important;
    font-weight: bold;
   
}
a {
    color:black;
    font-weight: bold;  
}
        #qrcode {
            margin: auto;
            width: 30%;
            padding: 45px;
            flex: 3;
        }

        #qrcode canvas {
            margin: 79;
            display: block;
        }
    </style>

<script type="text/javascript">
    const getQRRecommendedSize = (element) => {
        if (QR_SIZE <= 0) {
            width = element.clientWidth;
            console.debug("QR size check: width =", width);
            height = element.clientHeight;
            console.debug("QR size check: height =", height);

            return Math.min(width, height);
        } else {
            return QR_SIZE;
        }
    };

    const qr_init = () => {
        const qrcode = document.getElementById("qrcode");
        const input_area = document.getElementById("input");
        const error = document.getElementById("error");

        const showErrorMessage = (message) => {
            console.log("Error:", message);

            error.innerHTML = ""; // remove current children
            const messageElement = document.createTextNode(message);
            error.appendChild(messageElement);

            error.style.display = "block";
            qrcode.style.display = "none";
        };

        
        console.info("QR code error correction level:", ERROR_CORRECTION_LEVEL)
        
        const updateQRCode = () => {
            const qr_size = Math.max(getQRRecommendedSize(qrcode) - 10, 50); // remove 2 * 5px for the paddings
            console.info("QR code size in pixels:", qr_size);

            text = 'https://europa.eu/europass/en';
            if (!text) {
                showErrorMessage("You need to type something in the box below! The text you type will then be rendered as a QR code.");
            } else if (text.length > MAX_TEXT_LENGTH) {
                // This value was generated by trial and error
                showErrorMessage(`Your text is ${text.length} characters long. Sadly, due to technical limitations, the maximum size QR code this app can generate is ${MAX_TEXT_LENGTH} characters. Try splitting your text into multiple smaller parts.`)
            } else {
                const qr_was_shown = qrcode.style.display == "block";
                console.log("Was QR shown:", qr_was_shown);

                error.style.display = "none";
                qrcode.style.display = "block";
                try {
                    qrcode.innerHTML = ""; // delete the old QR codes
                    QrCreator.render({
                        text: text,
                        radius: 0.0, // square pixels
                        ecLevel: ERROR_CORRECTION_LEVEL,
                        fill: '#000000',
                        background: "#ffffff",
                        size: qr_size,
                    }, qrcode);

                    if (!qr_was_shown) {
                        // if no qr code was shown before, the size is screwed up.
                        // So we wait a bit and update the QR code to get the correct size
                        setTimeout(updateQRCode, 50);
                    
                    }
                } catch (error) {
                    showErrorMessage("Failed to generate the QR code! Please try a shorter text and try removing special characters and emojis. If you are a programmer, look in the prowser console for the error message");
                    console.error("QR code generation error", error);
                }
            }
        };

        updateQRCode();
        
        // Update the QR code whenever the text or the window size changes
        input_area.addEventListener("input", updateQRCode);
        window.addEventListener("resize", updateQRCode);
 
    }
    window.addEventListener("load", qr_init);
    </script>

   


<script src="assets/js/bootstrap.min.js"></script>
</body>
</html>

proiect_IS-main/templates/QR/QandA.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>Send Email</title>
  </head>
  <body>
    {% comment %} aici modifici sa nu mai ai pagina urata {% endcomment %}
    {% if messageSent %}
    
    <div class="container"><br></br>
      {% comment %} <div class="alert alert-success" role="alert">
        Email successfully sent <a href="#" class="alert-link"></a>
      </div>
     </div> {% endcomment %}
     <div class="p-1">
      <a href="{% url 'home' %}" class="btn btn-success btn-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Enter in your account" tabindex="-1" role="button" aria-disabled="true"><i class="fa fa-home"></i>Home</a>
  </div> 
    <div class="card">
      <div class="card-body">
      
        <p class="card-text"><div class="alert alert-success" role="alert">
          Email successfully sent <a href="#" class="alert-link"></a>
        </div></p>
      
      </div><div class="col-md-4">
      <img src="https://thumbs.dreamstime.com/b/send-us-message-glassy-green-round-button-isolated-abstract-illustration-97495097.jpg" class="card-img-bottom">
    </div>
  </div>

    {% else %}
   
    <div class="card mb-7" style="max-width: 940px;">
      <div class="row g-7">
        <div class="col-md-4">
          <a href="{% url 'home' %}"><img src="https://th.bing.com/th/id/OIP.JFqT7KZtRP-EYjpJVVfqyQHaEU?pid=ImgDet&w=1200&h=700&rs=1" class="img-fluid center"></a>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"> <div class="alert alert-primary" role="alert">
              Send an E-mail about CV issue<a href="#" class="alert-link"></a>
</div></h5>
            <p class="card-text">


              <h1>Contact Us</h1>
              <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}<div class="form-row">
            <div class="form-group col-lg-12 col-md-12 col-sm-12 col-12">
                <label for="attach" class="form-label">Please attach your CV / resume in PDF format</label>
  <input type="file" name="attach" id="attach" onchange="return fileValidation()" accept="application/pdf,application/vnd.ms-excel" class="form-control" required>
            </div>
          </div>
          <div class="form-actions">
            <button type="submit">Send</button>
          </div>
      </form>


            </p>
              </div>
        </div>
      </div>
   
{% comment %}    
    <div class="container">
      <div class="alert alert-primary" role="alert">
                         Send an E-mail about CV issue<a href="#" class="alert-link"></a>
      </div> {% endcomment %}
      
      
      {% comment %} <form method="post">
      
        <input type="hidden" name="csrfmiddlewaretoken" value="vgyNsxCvRbmRfArHBNaJJBYrCsDbF2AZtkmKLZ20rbocnU0dcSZN1uM3IQXfYrLL"> <p><label for="id_recipient">Email:</label> <input type="email" name="recipient" required id="id_recipient"></p>
<p><label for="id_message">Message:</label> <textarea name="message" cols="40" rows="10" required id="id_message">
</textarea></p>


        <br />
        <div class="text-center">
          <input
            type="submit"
            class="btn btn-primary btn-lg"
            style="width: 100%"
            value="Send e-mail"
          />
        </div>
      </form> {% endcomment %}
    </div>
    {% endif %}
  </body>
</html>